/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedOfficeRouteImport } from './routes/_authenticated/office'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminClassesIndexRouteImport } from './routes/_authenticated/admin.classes.index'
import { Route as AuthenticatedAdminClassesClassIdRouteImport } from './routes/_authenticated/admin.classes.$classId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfficeRoute = AuthenticatedOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesIndexRoute =
  AuthenticatedAdminClassesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClassesRoute,
  } as any)
const AuthenticatedAdminClassesClassIdRoute =
  AuthenticatedAdminClassesClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedAdminClassesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/office': typeof AuthenticatedOfficeRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/admin/classes/': typeof AuthenticatedAdminClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/admin/classes': typeof AuthenticatedAdminClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/office': typeof AuthenticatedOfficeRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/_authenticated/admin/classes/': typeof AuthenticatedAdminClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/office'
    | '/teacher'
    | '/admin/classes'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/'
    | '/admin/classes/$classId'
    | '/admin/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/office'
    | '/teacher'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin'
    | '/admin/classes/$classId'
    | '/admin/classes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/office'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/classes/$classId'
    | '/_authenticated/admin/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/office': {
      id: '/_authenticated/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof AuthenticatedOfficeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes/': {
      id: '/_authenticated/admin/classes/'
      path: '/'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AuthenticatedAdminClassesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClassesRoute
    }
    '/_authenticated/admin/classes/$classId': {
      id: '/_authenticated/admin/classes/$classId'
      path: '/$classId'
      fullPath: '/admin/classes/$classId'
      preLoaderRoute: typeof AuthenticatedAdminClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedAdminClassesRoute
    }
  }
}

interface AuthenticatedAdminClassesRouteChildren {
  AuthenticatedAdminClassesClassIdRoute: typeof AuthenticatedAdminClassesClassIdRoute
  AuthenticatedAdminClassesIndexRoute: typeof AuthenticatedAdminClassesIndexRoute
}

const AuthenticatedAdminClassesRouteChildren: AuthenticatedAdminClassesRouteChildren =
  {
    AuthenticatedAdminClassesClassIdRoute:
      AuthenticatedAdminClassesClassIdRoute,
    AuthenticatedAdminClassesIndexRoute: AuthenticatedAdminClassesIndexRoute,
  }

const AuthenticatedAdminClassesRouteWithChildren =
  AuthenticatedAdminClassesRoute._addFileChildren(
    AuthenticatedAdminClassesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOfficeRoute: typeof AuthenticatedOfficeRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOfficeRoute: AuthenticatedOfficeRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
